SELECT *
FROM EMP
WHERE JOB='SALESMAN';

SELECT *
FROM EMP
WHERE SAL> ANY (SELECT SAL FROM EMP WHERE JOB='SALESMAN');

SELECT *
FROM EMP
WHERE SAL < ANY(SELECT SAL FROM EMP WHERE DEPTNO=30);

SELECT *
FROM EMP
WHERE SAL < ALL(SELECT SAL FROM EMP WHERE DEPTNO=30);

SELECT *
FROM EMP
WHERE EXISTS (SELECT ENAME FROM EMP WHERE DEPTNO=10);

SELECT *
FROM EMP
WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, SAL FROM EMP WHERE DEPTNO=30);

SELECT * FROM (SELECT *FROM EMP WHERE DEPTNO=10)
WHERE SAL>=2000;

SELECT * 
FROM (SELECT * FROM EMP WHERE DEPTNO=10),
        (SELECT* FROM DEPT)
        WHERE SAL>=2000;
        
SELECT * 
FROM (SELECT * FROM EMP WHERE DEPTNO=10) E,
        (SELECT* FROM DEPT)D
        WHERE SAL>=2000 AND E.DEPTNO = D.DEPTNO; 

SELECT ROWNUM ENMAE, SAL
FROM (SELECT * FROM EMP ORDER BY SAL DESC);

SELECT ROWNUM ENMAE, SAL
FROM (SELECT * FROM EMP ORDER BY SAL DESC)
WHERE ROWNUM<=3;

SELECT JOB,EMPNO,ENAME,SAL,DEPTNO
FROM EMP
WHERE JOB =( SELECT JOB FROM EMP WHERE ENAME='ALLEN');

SELECT JOB,EMPNO,ENAME,SAL,EMP.DEPTNO,DNAME
FROM EMP,DEPT
WHERE JOB =( SELECT JOB FROM EMP WHERE ENAME='ALLEN')
AND EMP.DEPTNO = DEPT.DEPTNO;

SELECT JOB,EMPNO,ENAME,SAL,EMP.DEPTNO,DNAME
FROM EMP
INNER JOIN DEPT
ON EMP.DEPTNO= DEPT.DEPTNO 
WHERE JOB =( SELECT JOB FROM EMP WHERE ENAME='ALLEN');

SELECT EMPNO, ENAME , SAL, GRADE
FROM EMP,SALGRADE
WHERE SAL BETWEEN LOSAL AND HISAL
ORDER BY ENAME,GRADE;

SELECT EMPNO, ENAME, SAL GRADE
FROM EMP INNER JOIN salgrade
ON SAL BETWEEN LOSAL AND HISAL
ORDER BY ENAME,GRADE;

SELECT ENAME, JOB, EMP.DEPTNO, DNAME, LOC
FROM EMP, DEPT
WHERE EMP.DEPTNO = DEPT.DEPTNO
AND EMP.DEPTNO=10
AND JOB NOT IN (SELECT DISTINCT JOB FROM EMP WHERE DEPTNO=30);


SELECT EMP.ENAME, EMP.JOB, EMP.SAL, SALGRADE.GRADE
    FROM EMP INNER JOIN SALGRADE
    ON SAL BETWEEN LOSAL AND HISAL
WHERE SAL > (SELECT MAX(SAL) FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY SAL DESC;

SELECT EMP.ENAME, EMP.JOB, EMP.SAL, SALGRADE.GRADE
    FROM EMP INNER JOIN SALGRADE
    ON SAL BETWEEN LOSAL AND HISAL
WHERE SAL > ALL (SELECT SAL FROM EMP WHERE JOB = 'SALESMAN')
ORDER BY SAL DESC;

